#!/usr/bin/env node
// Render benchmark runs into the two things that get committed (issue 257).
//
// `src-tauri/benches/repo_bench.rs` writes one JSON document per fixture, full
// of raw samples. This turns the set of them into:
//
//   * `docs/dev/benchmark.json` — the published record, summary statistics only,
//     read by `test/benchmark.test.ts`;
//   * the table block inside `docs/dev/performance.md`, between its generated
//     markers — the developer-facing record, with every operation, the `git`
//     baseline beside it and the ratio between them.
//
// **Both are generated, and neither is hand-editable.** That is the whole point
// of the exercise: the site is supposed to print a number somebody measured,
// and the way a measured number turns back into an adjective is somebody
// nudging it in a hurry.
//
// The markdown is rendered from the PUBLISHED record rather than from the raw
// runs, and that indirection is the guard test's whole leverage: the test
// re-renders it from the committed JSON and compares it to the committed
// markdown, so the two can only agree if both came from one run. Rendering from
// the raw results — which are not committed — would leave the guard able to
// check only that the markdown parses.
//
// The raw sample arrays are deliberately NOT committed. They are what makes a
// result checkable, so they stay in `$PGBENCH_HOME/results/`, but a committed
// file that churns forty floating-point numbers per run is a file nobody reads
// the diff of.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

/** Operations in the order the tables print them: roughly the order a user
 *  meets them, opening a repository first and browsing the tree last, rather
 *  than the order the harness happens to measure. */
export const OP_ORDER = [
  "open",
  "open_screen",
  "open_screen_ipc",
  "status",
  "log_first_page",
  "log_page_deep",
  "branches",
  "tags",
  "diff_commit",
  "diff_workdir_file",
  "file_history",
  "list_all_files",
];

/** Title and one-line framing per fixture. Lives here rather than in the JSON
 *  because it is editorial — what the repository is FOR — while everything the
 *  harness writes is measured. */
export const FIXTURES = {
  linux: {
    title: "torvalds/linux",
    kind: "real",
    blurb:
      "A real clone of the Linux kernel: the repository people mean when they " +
      "say a git client is slow.",
  },
  deep: {
    title: "deep",
    kind: "generated",
    blurb:
      "50,000 commits over a small tree — the size past which GitKraken's own " +
      "users report native clients beating it.",
  },
  wide: {
    title: "wide",
    kind: "generated",
    blurb:
      "50,000 tracked files with every one of them modified, plus 5,000 " +
      "untracked — a monorepo just after a codemod.",
  },
  refs: {
    title: "refs",
    kind: "generated",
    blurb:
      "5,000 branches and 2,000 tags over a short history — a long-lived " +
      "repository nobody prunes.",
  },
};

/**
 * What each row is CALLED, as opposed to what it measured.
 *
 * Editorial, so it lives here beside `FIXTURES` rather than in the harness, for
 * the same reason the fixture blurbs do: rewording a table heading should not
 * mean recompiling a benchmark and re-running it against a six-gigabyte clone.
 * The harness's own label is the fallback for an op this map has not met.
 *
 * `log_page_deep` is why the rule earned its keep. Its harness label named the
 * commit range it reaches — which is a lie on any fixture with less history
 * than that, and `wide` has exactly one commit.
 */
export const OP_LABELS = {
  open: "Open the repository",
  open_screen: "Everything the first screen needs, at once",
  open_screen_ipc: "…including encoding it all for the webview",
  status: "Working-tree status",
  log_first_page: "First page of history",
  log_page_deep: "Ten pages into history",
  branches: "List every branch",
  tags: "List every tag",
  diff_commit: "Diff the selected commit",
  diff_workdir_file: "Diff one modified file",
  file_history: "History of one file",
  list_all_files: "Browse the whole tree",
};

/**
 * "1 commits" is the sort of thing that makes a published table look
 * unproofread, and the counts come from the harness as free text. Fixing it
 * where it is READ rather than where it is measured keeps the harness's job to
 * measuring.
 */
export function tidyScale(scale) {
  return String(scale).replace(/^1 ([a-z]+)$/, (whole, word) => {
    if (word.endsWith("ies")) return `1 ${word.slice(0, -3)}y`;
    if (/(ch|sh|x|s)es$/.test(word)) return `1 ${word.slice(0, -2)}`;
    if (word.endsWith("s")) return `1 ${word.slice(0, -1)}`;
    return whole;
  });
}

export const BEGIN =
  "<!-- BEGIN BENCHMARK RESULTS — generated by scripts/bench.sh, do not edit -->";
export const END = "<!-- END BENCHMARK RESULTS -->";

/** Milliseconds, at a precision the measurement can actually support.
 *
 *  Three significant figures at most, and seconds once past a thousand
 *  milliseconds: "5728.58 ms" implies a repeatability no wall-clock number on a
 *  general-purpose machine has, and reading it as 5.73 s is how anybody would
 *  say it out loud anyway. */
export function fmtMs(v) {
  if (v == null) return "—";
  if (v >= 1000) return `${(v / 1000).toFixed(2)} s`;
  if (v >= 100) return `${v.toFixed(0)} ms`;
  if (v >= 10) return `${v.toFixed(1)} ms`;
  return `${v.toFixed(2)} ms`;
}

export function fmtRatio(v) {
  if (v == null) return "—";
  if (v >= 10) return `${v.toFixed(0)}×`;
  if (v >= 1) return `${v.toFixed(1)}×`;
  return `${v.toFixed(2)}×`;
}

export function fmtMb(v) {
  return v == null ? "—" : `${v.toFixed(0)} MB`;
}

function thousands(n) {
  return Number(n).toLocaleString("en-US");
}

/** One line describing the repository, for the table caption. Built from what
 *  the harness counted rather than from the fixture definition, so a fixture
 *  that generated wrong is visible in the published document. */
export function describeRepo(r) {
  const parts = [
    `${thousands(r.commits)} commits`,
    `${thousands(r.trackedFiles)} tracked files`,
  ];
  if (r.branches > 1) parts.push(`${thousands(r.branches)} branches`);
  if (r.tags > 0) parts.push(`${thousands(r.tags)} tags`);
  if (r.dirtyEntries > 0) parts.push(`${thousands(r.dirtyEntries)} changed entries`);
  return parts.join(" · ");
}

/**
 * What `git` spent on the WORK, with process start-up taken back out.
 *
 * Every `git` invocation pays for a `fork`, an `exec`, the dynamic loader and
 * git's own start-up before it reads a byte — over ten milliseconds on an
 * M-series Mac, which is more than most of the operations here take in total.
 * We pay none of it: the backend is libgit2, in process.
 *
 * So the ratio is against git's work, not its wall clock, and that choice is
 * deliberately the one that makes US look worse. Comparing against the wall
 * clock would hand us a ten-millisecond head start on every row and quietly
 * turn a loss into a win on any operation git finishes quickly.
 *
 * Scaled by the invocation COUNT, because a baseline can be several processes —
 * `status`'s is three (see the module doc on why), so it pays the floor three
 * times.
 */
export function gitWorkMs(op, floorMs) {
  if (op.gitMedianMs == null || !op.gitInvocations) return null;
  return Math.max(0, op.gitMedianMs - floorMs * op.gitInvocations);
}

/**
 * Is what is left big enough to divide by?
 *
 * When start-up is most of the baseline, the remainder is the difference of two
 * similar noisy numbers and a ratio against it is arithmetic, not measurement.
 * A quarter is the line: below it the row prints † and no ratio, which is the
 * honest answer for `status` on a clean tree, where git's three processes cost
 * 40 ms and 37 ms of that is launching them.
 */
export function isFloorBound(op, floorMs) {
  const work = gitWorkMs(op, floorMs);
  if (work == null || op.gitMedianMs == null) return false;
  return work <= 0 || work < op.gitMedianMs * 0.25;
}

/** The ratio against git's work, or null when that work is unmeasurable. */
export function ratioToGit(op, floorMs) {
  if (op.repeatMedianMs == null || isFloorBound(op, floorMs)) return null;
  const work = gitWorkMs(op, floorMs);
  return work && work > 0 ? op.repeatMedianMs / work : null;
}

function orderOps(ops) {
  const rank = (op) => {
    const i = OP_ORDER.indexOf(op);
    return i === -1 ? OP_ORDER.length : i;
  };
  return [...ops].sort((a, b) => rank(a.op) - rank(b.op));
}

export function renderTable(fixture) {
  const head = [
    "Operation",
    "Result size",
    "First call",
    "Repeat",
    "p95",
    "`git` work",
    "vs `git`",
  ];
  const rows = fixture.operations.map((o) => [
    o.label,
    tidyScale(o.scale),
    fmtMs(o.firstMs),
    fmtMs(o.repeatMedianMs),
    fmtMs(o.repeatP95Ms),
    // git's WORK, not its wall clock — see `gitWorkMs`. The dagger marks a
    // baseline where start-up swamped the work, so there was nothing left to
    // compare; that row's ratio is deliberately absent rather than impressive.
    o.gitFloorBound ? "†" : fmtMs(o.gitWorkMs),
    fmtRatio(o.ratioToGit),
  ]);
  const line = (cells) => `| ${cells.join(" | ")} |`;
  return [line(head), line(head.map(() => "---")), ...rows.map(line)].join("\n");
}

export function renderSoak(soak) {
  if (!soak) return null;
  const drift =
    soak.firstHalfMedianMs && soak.secondHalfMedianMs
      ? (soak.secondHalfMedianMs / soak.firstHalfMedianMs - 1) * 100
      : null;
  return (
    `${thousands(soak.iterations)} first-screen fan-outs over ${soak.minutes} minutes. ` +
    `Resident memory ${fmtMb(soak.rssStartMb)} → ${fmtMb(soak.rssEndMb)} ` +
    `(peak ${fmtMb(soak.rssPeakMb)}). ` +
    `Median fan-out ${fmtMs(soak.firstHalfMedianMs)} in the first half, ` +
    `${fmtMs(soak.secondHalfMedianMs)} in the second` +
    (drift == null ? "." : ` — ${drift >= 0 ? "+" : ""}${drift.toFixed(1)}%.`)
  );
}

/** The table block, rendered from the published record. */
export function renderMarkdown(data) {
  const out = [];
  const m = data.machine;
  out.push(
    `Measured on ${m.cpu} (${m.cores} cores, ${m.memoryGb} GB, ${m.os}) with ` +
      `${m.gitVersion}, on ${data.measuredOn}. Up to ${data.iterations} repeats ` +
      `per operation, time-boxed to ${data.budgetSeconds}s each — so a cheap ` +
      `operation gets the full count and an expensive one gets at least three. ` +
      `The published record records how many each row actually took.`,
  );
  out.push("");
  out.push(
    "The **`git` work** column is that baseline's wall clock with process " +
      `start-up subtracted (${fmtMs(data.gitSpawnFloorMs)} per invocation on ` +
      "this machine, measured), because we pay none of it — the backend is " +
      "libgit2, in process. That is deliberately the comparison that makes us " +
      "look worse: against git's wall clock we would get a ten-millisecond " +
      "head start on every row. **†** marks a baseline where start-up swamped " +
      "the work, leaving a remainder too small to divide by; those rows print " +
      "no ratio rather than a flattering one.",
  );
  out.push("");
  for (const fixture of data.fixtures) {
    out.push(`### ${fixture.title}`);
    out.push("");
    if (fixture.blurb) out.push(fixture.blurb);
    out.push("");
    out.push(`*${describeRepo(fixture.repository)}*`);
    out.push("");
    out.push(renderTable(fixture));
    const soak = renderSoak(fixture.soak);
    if (soak) {
      out.push("");
      out.push(`**Soak.** ${soak}`);
    }
    out.push("");
  }
  return out.join("\n").trimEnd();
}

/** The published record. Summary statistics only — see the header note on why
 *  the samples stay out of the repository.
 *
 *  It lives beside `performance.md` rather than under `site/` because nothing
 *  renders it yet: publishing these figures on the marketing site waits on the
 *  log-walk work, and a data file under `site/**` would redeploy the site on
 *  every re-measurement for no visible change. */
export function buildPublishedRecord(runs) {
  const m = runs[0].machine;
  return {
    measuredOn: new Date().toISOString().slice(0, 10),
    machine: {
      cpu: m.cpu,
      cores: m.cores,
      memoryGb: m.memoryGb,
      os: `${m.os}/${m.arch}`,
      gitVersion: m.git,
    },
    iterations: runs[0].iterations,
    budgetSeconds: runs[0].budgetSeconds,
    /** What one `git` invocation costs before doing anything, measured. */
    gitSpawnFloorMs: runs[0].gitSpawnFloorMs,
    fixtures: runs.map((run) => ({
      key: run.fixture,
      title: FIXTURES[run.fixture]?.title ?? run.fixture,
      kind: FIXTURES[run.fixture]?.kind ?? "generated",
      blurb: FIXTURES[run.fixture]?.blurb ?? "",
      repository: run.repository,
      /** Measured per run, because it is a property of the machine at the time
       *  and not a constant. The note under the tables quotes the first. */
      gitSpawnFloorMs: run.gitSpawnFloorMs,
      operations: orderOps(run.operations).map((o) => ({
        op: o.op,
        label: OP_LABELS[o.op] ?? o.label,
        scale: tidyScale(o.scale),
        /** How many repeats this row actually took — see the time box. */
        samples: o.samples,
        firstMs: o.firstMs,
        repeatMedianMs: o.repeatMedianMs,
        repeatP95Ms: o.repeatP95Ms,
        gitCommand: o.gitCommand,
        gitInvocations: o.gitInvocations,
        /** The baseline's wall clock, start-up included. */
        gitMedianMs: o.gitMedianMs,
        /** …and with start-up subtracted, which is what the ratio divides by. */
        gitWorkMs: gitWorkMs(o, run.gitSpawnFloorMs),
        // Derived HERE rather than in the harness: whether a baseline is
        // comparable is a judgement about what may be published, and it belongs
        // with the thing that publishes it.
        gitFloorBound: isFloorBound(o, run.gitSpawnFloorMs),
        ratioToGit: ratioToGit(o, run.gitSpawnFloorMs),
      })),
      soak: run.soak ?? null,
    })),
  };
}

export function splice(doc, block) {
  const a = doc.indexOf(BEGIN);
  const b = doc.indexOf(END);
  if (a === -1 || b === -1) {
    throw new Error("docs/dev/performance.md is missing its generated markers");
  }
  return doc.slice(0, a + BEGIN.length) + "\n\n" + block + "\n\n" + doc.slice(b);
}

function arg(argv, name, fallback) {
  const at = argv.indexOf(name);
  return at === -1 ? fallback : argv[at + 1];
}

function main() {
  const argv = process.argv.slice(2);
  const results = arg(argv, "--results");
  const root = arg(argv, "--root", process.cwd());
  const only = arg(argv, "--fixtures", "").split(",").filter(Boolean);
  const print = argv.includes("--print");

  // Ordered so the real repository leads and the generated ones follow, which
  // is the order a reader wants: the headline first, then the dimensions that
  // explain it.
  const order = ["linux", "deep", "wide", "refs"];
  const names = (only.length ? only : order).sort(
    (a, b) => order.indexOf(a) - order.indexOf(b),
  );

  const runs = [];
  for (const name of names) {
    const path = join(results, `${name}.json`);
    if (!existsSync(path)) {
      console.error(`  no results for ${name} (${path}) — skipping`);
      continue;
    }
    runs.push(JSON.parse(readFileSync(path, "utf8")));
  }
  if (!runs.length) throw new Error("no results to render");

  const data = buildPublishedRecord(runs);
  const markdown = renderMarkdown(data);
  if (print) {
    console.log(markdown);
    return;
  }

  const dataPath = join(root, "docs/dev/benchmark.json");
  writeFileSync(dataPath, JSON.stringify(data, null, 2) + "\n");
  console.log(`  wrote ${dataPath}`);

  const docPath = join(root, "docs/dev/performance.md");
  writeFileSync(docPath, splice(readFileSync(docPath, "utf8"), markdown));
  console.log(`  wrote ${docPath}`);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
